### ISSUE TITLE
Wemo sometimes ignores SSDP Queries

### ISSUE THREAD

**Issue by ShaneMcC** [ShaneMcC/wemo#1]
Wemo sometimes ignores SSDP Queries, we should poke it a couple of times to ensure it replies, or cache which devices we've found in the past and try them anyway.

**Comment by csmith** [comment]
It looks like you're setting the socket timeout to 2 seconds but sending an MX value of 3 which means recipients will wait between 0 and 3 seconds to reply, which means you'll miss about 1/3 responses anyway.

**Comment by ShaneMcC** [comment]
Multiple packets, and/or sending the correct MX value appears to have resolved this.
