### ISSUE TITLE
More fine-tuned submit return codes

### ISSUE THREAD

**Issue by tsumaru720** [ShaneMcC/wemo#10]
Recently came accross a problem whereby permissions for the already existing RRD changed and web/submit.php could therefore not update RRD. It still seemed to return success to the probe though so the probe removed what it had just submitted from its local copy.

From what I can tell you submit everything gathered by the probe in one go, so would be nice if the probe generated an ID per item being submitted which would allow submit.php to return more tailored success/fail to the probe based on ID. If for whatever reason the probe gets a fail result, it should keep the value locally until a successful submit

**Comment by ShaneMcC** [comment]
We submit everything one-by-one (bulk-submission would be a separate issue), so the complexity of IDs shouldn't be needed.

`submit.php` doesn't check the return value from `updateRRD()` for success/fail, it just checks to see if the RRD exists and assumes that update passes.

**Comment by tsumaru720** [comment]
works for me - i only skim read the code

**Comment by tsumaru720** [comment]
rrdtool appears to return

```
string(212) "array(3) {
  ["stdout"]=>
  string(93) "ERROR: opening '/opt/wemo/web/rrds//desk/221xxxxxxxx038/instantPower.rrd': Permission denied
"
  ["stderr"]=>
  string(0) ""
  ["status"]=>
  bool(false)
}

```
