### ISSUE TITLE
Specifying device IPs

### ISSUE THREAD

**Issue by tsumaru720** [ShaneMcC/wemo#3]
An option to provide a list of known device IPs could be handy

**Comment by ShaneMcC** [comment]
http://stackoverflow.com/questions/28870802/why-cant-i-get-upnp-unicast-m-search-to-work-instead-of-multicast-m-search

Don't need MX for non-multicast.

**Comment by tsumaru720** [comment]
Doesnt seem to work when polling IPs directly :(
