### ISSUE TITLE
Add header/footer template for web frontend

### ISSUE THREAD

**Issue by tsumaru720** [ShaneMcC/wemo#6]
Rather than hard-coding it into index.php, could have a header and footer page that allows customization of how the overview page is displayed

Ultimately I was looking for something like this, but makes sense to template them and include proper HTML headers/Footers rather than just dump <img> tags :)

```
<META HTTP-EQUIV="Cache-Control" content="no-cache">
<META HTTP-EQUIV="Pragma" CONTENT="no-cache">
<META HTTP-EQUIV="Refresh" CONTENT="60">
```

**Comment by ShaneMcC** [comment]
The current web view is due a complete overhaul anyway as it was just a temporary "I want to see the graphs" view.

The plan is to template it :)
